#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Illuminate\Contracts\Console\Kernel;

$kernel = app(Kernel::class);
$status = $kernel->handle(
    $input = Illuminate\Console\Input\ArgvInput::createFromArgv(),
    new Illuminate\Console\OutputStyle($input, new Symfony\Component\Console\Output\ConsoleOutput)
);

$kernel->terminate($input, $status);
exit($status);
